
surface.CreateFont("Metroid Prime LogBook", {
	font      = "Logbook Prime v2",
	extended  = false,
	size      = 26,
	weight    = 500,
	blursize  = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic    = false,
	strikeout = false,
	symbol    = false,
	rotary    = false,
	shadow    = false,
	additive  = false,
	outline   = false,
});

surface.CreateFont("Metroid Prime Visor UI", {
	font      = "Logbook Prime v2",
	extended  = false,
	size      = 22,
	weight    = 500,
	blursize  = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic    = false,
	strikeout = false,
	symbol    = false,
	rotary    = false,
	shadow    = false,
	additive  = false,
	outline   = false,
});

surface.CreateFont("Metroid Prime Visor UI Small", {
	font      = "Logbook Prime v2",
	extended  = false,
	size      = 18,
	weight    = 500,
	blursize  = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic    = false,
	strikeout = false,
	symbol    = false,
	rotary    = false,
	shadow    = false,
	additive  = false,
	outline   = false,
});

surface.CreateFont("Metroid Prime Visor UI Bold", {
	font      = "Logbook Prime v2",
	extended  = false,
	size      = 22,
	weight    = 800,
	blursize  = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic    = false,
	strikeout = false,
	symbol    = false,
	rotary    = false,
	shadow    = false,
	additive  = false,
	outline   = false,
});