{
   "Spike 6":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 225 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":120,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "Material":"models/metroid/effects/ice/MAT_0_0",
      "StartAxisScale":"[0.30000001192093 0.30000001192093 1.3500000238419]"
   },
   "Spike 3":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.025,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 195 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.40000000596046 0.40000000596046 1.2000000476837]"
   },
   "Spike 4":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.025,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 35 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.40000000596046 0.40000000596046 1.2000000476837]"
   },
   "Spike 1":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 100 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.30000001192093 0.30000001192093 1.3500000238419]"
   },
   "Spike 2":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 135 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":120,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "Material":"models/metroid/effects/ice/MAT_0_0",
      "StartAxisScale":"[0.28000000119209 0.28000000119209 1.3500000238419]"
   },
   "Spike 7":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.025,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 -50 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.44999998807907 0.44999998807907 1.0499999523163]"
   },
   "Core":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "ColorFunction":"Sine",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "LifeTime":0.65,
      "Angles":"{0 -45 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":130,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":0,
      "RotationNormal":"[0 0 1]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.80000001192093 0.80000001192093 1.2000000476837]"
   },
   "Spike 8":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 -70 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "StartAxisScale":"[0.5 0.5 1]"
   },
   "Spike 5":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{60 -20 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":false,
      "EndScale":140,
      "InheritPos":false,
      "StartAlpha":255,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "ColorFunction":"Sine",
      "LifeTime":0.65,
      "StartScale":0,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "RotationNormal":"[0 0 1]",
      "UseEndAlpha":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/icechunk.mdl",
      "Material":"models/metroid/effects/ice/MAT_0_0",
      "StartAxisScale":"[0.40000000596046 0.40000000596046 1]"
   }
}