{
   "Icicle":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":false,
      "EndAlpha":0,
      "ColorFunction":"Sine",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "LifeTime":0.6,
      "UseEndAlpha":false,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "AxisScaleFunctionMod":1,
      "Looping":false,
      "ConstantRotation":true,
      "EndAxisScale":"[1 1 1]",
      "UseEndAxisScale":false,
      "StartScale":5,
      "StartAlpha":255,
      "AxisScaleFunction":"Sine",
      "ScaleFunctionMod":1,
      "InheritPos":false,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "RotationNormal":"[0 0 1]",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritLifeTime":false,
      "ScaleFunction":"Sine",
      "Angles":"{0 0 0}",
      "Model":"models/metroid/effects/icicle.mdl",
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"",
      "UseEndScale":true,
      "EndScale":65,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   }
}