{
   "Outer Shell White":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.15,
      "AlphaFunctionMod":3.5,
      "UseEndColor":false,
      "EndAlpha":50,
      "ColorFunction":"Sine",
      "StartRotation":0,
      "RotationFunction":"OutSine",
      "LifeTime":0.7,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":50,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":15,
      "RotationNormal":"[1 1 0]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"Sine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 -1 1]",
      "EndRotation":180,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Outer Shell Dark Blue":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.1,
      "AlphaFunctionMod":1.8,
      "UseEndColor":true,
      "EndAlpha":75,
      "ColorFunction":"Sine",
      "StartRotation":45,
      "RotationFunction":"Sine",
      "LifeTime":0.7,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":0,
         "g":12,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":47.5,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":15,
      "RotationNormal":"[0 1 1]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"InOutSine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[-1 1 0]",
      "EndRotation":225,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Outer Shell Blue":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":0.8,
      "Delay":0,
      "AlphaFunctionMod":1.8,
      "UseEndColor":true,
      "EndAlpha":150,
      "ColorFunction":"InBounce",
      "StartRotation":90,
      "RotationFunction":"Sine",
      "LifeTime":0.7,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":0,
         "g":0,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":45,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":15,
      "RotationNormal":"[1 0 1]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"InOutSine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[1 1 -1]",
      "EndRotation":270,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Inner Shell White":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1.5,
      "Delay":0.15,
      "AlphaFunctionMod":3.5,
      "UseEndColor":true,
      "EndAlpha":75,
      "ColorFunction":"Sine",
      "StartRotation":0,
      "RotationFunction":"OutSine",
      "LifeTime":0.8,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":0,
         "g":12,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":35,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":7.5,
      "RotationNormal":"[1 1 0]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"Sine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[0 -1 1]",
      "EndRotation":-180,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Inner Shell Dark Blue":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.1,
      "AlphaFunctionMod":1.8,
      "UseEndColor":true,
      "EndAlpha":50,
      "ColorFunction":"Sine",
      "StartRotation":45,
      "RotationFunction":"OutSine",
      "LifeTime":0.8,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":0,
         "g":12,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":33.75,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":7.5,
      "RotationNormal":"[1 -1 0]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"InOutSine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[-1 1 0]",
      "EndRotation":-135,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Inner Shell Blue":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":0.8,
      "Delay":0,
      "AlphaFunctionMod":1.8,
      "UseEndColor":true,
      "EndAlpha":100,
      "ColorFunction":"InBounce",
      "StartRotation":90,
      "RotationFunction":"OutSine",
      "LifeTime":0.8,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":0,
         "g":0,
         "b":255
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"InOutQuart",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":32.5,
      "InheritPos":false,
      "StartAlpha":0,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":7.5,
      "RotationNormal":"[1 1 0]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"InOutSine",
      "ConstantRotation":false,
      "EndAxisScale":"[1 1 1]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":255,
         "b":255
      },
      "Pos":"[1 1 -1]",
      "EndRotation":-180,
      "ScaleFunctionMod":1.45,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   }
}