{
   "Plane 6":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.175,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{15 95 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 5":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.165,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-20 40 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 4":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.155,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{20 45 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 3":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.175,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{30 80 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 9":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.205,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-5 90 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 2":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.135,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-40 45 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 8":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.195,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{120 50 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 1":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.125,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{5 65 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 7":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.185,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{25 35 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 10":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.215,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"OutSine",
      "StartAlpha":15,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":100,
         "g":155,
         "b":255
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":215,
         "g":235,
         "b":245
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{15 10 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   }
}