{
   "Plane 6":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.075,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{15 95 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 5":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.065,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-20 40 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 4":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.055,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{20 45 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 3":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.075,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{30 80 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 9":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.005,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-5 90 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 2":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.035,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{-40 45 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 8":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.095,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{120 50 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 1":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.025,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{5 65 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 7":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.085,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{25 35 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   },
   "Plane 10":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0.015,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/hud/v_beamchange.mdl",
      "UseEndAxisScale":false,
      "ColorFunction":"InSine",
      "StartAlpha":32,
      "ScaleFunctionMod":1,
      "InheritPos":true,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":255,
         "g":238,
         "b":35
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":246,
         "g":0,
         "b":255
      },
      "InheritLifeTime":false,
      "StartScale":10,
      "Angles":"{15 10 0}",
      "LifeTime":0.2,
      "Pos":"[0 0 0]",
      "EndRotation":0,
      "Material":"particles/missile/plane",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":false,
      "StartAxisScale":"[1 1 1]"
   }
}