{
  "shell1": {
    "Enable": true,
    "Skin": 0,
    "ColorFunctionMod": 1,
    "Delay": 0.1,
    "AlphaFunctionMod": 1.5,
    "UseEndColor": true,
    "EndAlpha": 0,
    "ColorFunction": "InCirc",
    "StartRotation": 0,
    "RotationFunction": "Sine",
    "LifeTime": 3.5,
    "UseEndAlpha": true,
    "BodyGroups": "0",
    "AlphaFunction": "Sine",
    "InheritAngles": false,
    "RotationFunctionMod": 1,
    "AxisScaleFunctionMod": 1,
    "Looping": false,
    "ConstantRotation": false,
    "EndAxisScale": "[1 1 0.77]",
    "UseEndAxisScale": false,
    "StartScale": 1,
    "StartAlpha": 10,
    "AxisScaleFunction": "Sine",
    "ScaleFunctionMod": 1.5,
    "InheritPos": true,
    "StartColor": {
      "r": 255,
      "g": 231,
      "b": 137
    },
    "RotationNormal": "[0 0 1]",
    "EndColor": {
      "r": 255,
      "g": 255,
      "b": 255
    },
    "InheritLifeTime": false,
    "ScaleFunction": "Sine",
    "Angles": "{0 0 0}",
    "Model": "models/metroid/effects/chargeball.mdl",
    "Pos": "[0 0 0]",
    "EndRotation": 360,
    "Material": "particles/powerbomb/core",
    "UseEndScale": true,
    "EndScale": 500,
    "UseEndRotation": true,
    "StartAxisScale": "[1 1 0.77]"
  },
  "shell2": {
    "Enable": true,
    "Skin": 0,
    "ColorFunctionMod": 1,
    "Delay": 1.1,
    "AlphaFunctionMod": 1.5,
    "UseEndColor": true,
    "EndAlpha": 0,
    "ColorFunction": "InCirc",
    "StartRotation": 0,
    "RotationFunction": "Sine",
    "LifeTime": 3.5,
    "UseEndAlpha": true,
    "BodyGroups": "0",
    "AlphaFunction": "Sine",
    "InheritAngles": false,
    "RotationFunctionMod": 1,
    "AxisScaleFunctionMod": 1,
    "Looping": false,
    "ConstantRotation": false,
    "EndAxisScale": "[1 1 0.77]",
    "UseEndAxisScale": false,
    "StartScale": 1,
    "StartAlpha": 10,
    "AxisScaleFunction": "Sine",
    "ScaleFunctionMod": 1.5,
    "InheritPos": true,
    "StartColor": {
      "r": 255,
      "g": 160,
      "b": 97
    },
    "RotationNormal": "[0 0 1]",
    "EndColor": {
      "r": 255,
      "g": 160,
      "b": 97
    },
    "InheritLifeTime": false,
    "ScaleFunction": "Sine",
    "Angles": "{0 0 0}",
    "Model": "models/metroid/effects/chargeball.mdl",
    "Pos": "[0 0 0]",
    "EndRotation": 360,
    "Material": "particles/powerbomb/core",
    "UseEndScale": true,
    "EndScale": 500,
    "UseEndRotation": true,
    "StartAxisScale": "[1 1 0.77]"
  }
}