{
   "Ring":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "ColorFunction":"InQuad",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "LifeTime":0.45,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":204,
         "g":162,
         "b":46
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":40,
      "InheritPos":false,
      "StartAlpha":200,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":15,
      "RotationNormal":"[0 0 1]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "EndAxisScale":"[1.2999999523163 1.2999999523163 0.050000000745058]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "Pos":"[0 0 0]",
      "EndRotation":270,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":true,
      "Model":"models/metroid/effects/plasma_ring.mdl",
      "StartAxisScale":"[1 1 0.5]"
   },
   "Spire 2":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1.5,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1.2999999523163 1.2999999523163 0.89999997615814]",
      "StartRotation":0,
      "RotationFunction":"OutBounce",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":false,
      "Model":"models/metroid/effects/plasma_ring.mdl",
      "UseEndAxisScale":true,
      "ColorFunction":"Sine",
      "StartAlpha":100,
      "ScaleFunctionMod":1,
      "InheritPos":false,
      "AxisScaleFunction":"InSine",
      "StartColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "ScaleFunction":"OutSine",
      "EndColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "InheritLifeTime":false,
      "StartScale":20,
      "Angles":"{0 0 0}",
      "LifeTime":0.5,
      "Pos":"[0 0 0]",
      "EndRotation":180,
      "Material":"",
      "UseEndScale":true,
      "EndScale":35,
      "UseEndRotation":true,
      "StartAxisScale":"[1.2000000476837 1.2000000476837 1]"
   },
   "Ring 2":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "ColorFunction":"InQuad",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "LifeTime":0.45,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":204,
         "g":162,
         "b":46
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "ScaleFunction":"Sine",
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":40,
      "InheritPos":false,
      "StartAlpha":200,
      "Material":"",
      "AxisScaleFunction":"Sine",
      "StartScale":15,
      "RotationNormal":"[0 0 1]",
      "AxisScaleFunctionMod":1,
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "EndAxisScale":"[1.3 1.3 0.2]",
      "UseEndAlpha":true,
      "StartColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "Pos":"[0 0 0]",
      "EndRotation":-270,
      "ScaleFunctionMod":1.5,
      "UseEndScale":true,
      "UseEndAxisScale":true,
      "Model":"models/metroid/effects/plasma_ring.mdl",
      "StartAxisScale":"[1 1 0.5]"
   },
   "Spire 1":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1.5,
      "UseEndColor":false,
      "EndAlpha":0,
      "EndAxisScale":"[1.2000000476837 1.2000000476837 1.2000000476837]",
      "StartRotation":0,
      "RotationFunction":"OutBounce",
      "AxisScaleFunctionMod":1.5,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":false,
      "Model":"models/metroid/effects/plasma_ring.mdl",
      "UseEndAxisScale":true,
      "ColorFunction":"Sine",
      "StartAlpha":100,
      "ScaleFunctionMod":1.5,
      "InheritPos":false,
      "AxisScaleFunction":"Sine",
      "StartColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "ScaleFunction":"Sine",
      "EndColor":{
         "r":217,
         "g":100,
         "b":46
      },
      "InheritLifeTime":false,
      "StartScale":20,
      "Angles":"{0 0 0}",
      "LifeTime":0.3,
      "Pos":"[0 0 0]",
      "EndRotation":5,
      "Material":"",
      "UseEndScale":true,
      "EndScale":30,
      "UseEndRotation":true,
      "StartAxisScale":"[1.2000000476837 1.2000000476837 1]"
   }
}