{
   "Outer":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":0.8,
      "Delay":0,
      "AlphaFunctionMod":3.25,
      "UseEndColor":true,
      "EndAlpha":80,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":224,
         "g":116,
         "b":67
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "StartScale":0,
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":65,
      "AxisScaleFunction":"Sine",
      "StartAlpha":0,
      "Material":"",
      "ScaleFunctionMod":2,
      "ColorFunction":"InOutQuart",
      "LifeTime":1.25,
      "RotationNormal":"[1 1 0]",
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "ScaleFunction":"OutQuart",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":242,
         "b":216
      },
      "Pos":"[0 2 10]",
      "EndRotation":125,
      "InheritPos":false,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Mid":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":0.8,
      "Delay":0,
      "AlphaFunctionMod":3.25,
      "UseEndColor":true,
      "EndAlpha":50,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":224,
         "g":116,
         "b":67
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "StartScale":0,
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":60,
      "AxisScaleFunction":"Sine",
      "StartAlpha":0,
      "Material":"",
      "ScaleFunctionMod":2,
      "ColorFunction":"InOutQuart",
      "LifeTime":1.25,
      "RotationNormal":"[1 1 1]",
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "ScaleFunction":"OutQuart",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":242,
         "b":216
      },
      "Pos":"[2 -2 5]",
      "EndRotation":90,
      "InheritPos":false,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Inner":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":0.8,
      "Delay":0,
      "AlphaFunctionMod":3.25,
      "UseEndColor":true,
      "EndAlpha":75,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "Angles":"{0 0 0}",
      "BodyGroups":"0",
      "EndColor":{
         "r":224,
         "g":116,
         "b":67
      },
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "StartScale":0,
      "Looping":false,
      "InheritLifeTime":false,
      "UseEndRotation":true,
      "EndScale":55,
      "AxisScaleFunction":"Sine",
      "StartAlpha":0,
      "Material":"",
      "ScaleFunctionMod":2,
      "ColorFunction":"InOutQuart",
      "LifeTime":1.25,
      "RotationNormal":"[1 1 -1]",
      "AlphaFunction":"Sine",
      "ConstantRotation":true,
      "ScaleFunction":"OutQuart",
      "UseEndAlpha":true,
      "StartColor":{
         "r":255,
         "g":242,
         "b":216
      },
      "Pos":"[-2 -2 5]",
      "EndRotation":110,
      "InheritPos":false,
      "UseEndScale":true,
      "UseEndAxisScale":false,
      "Model":"models/metroid/effects/supermissile_ball.mdl",
      "StartAxisScale":"[1 1 1]"
   },
   "Inner Ring":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1.5,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1.25]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"Sine",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/effects/supermissile_ring.mdl",
      "UseEndAxisScale":true,
      "ColorFunction":"Sine",
      "StartAlpha":125,
      "ScaleFunctionMod":1.25,
      "InheritPos":false,
      "AxisScaleFunction":"OutQuart",
      "StartColor":{
         "r":255,
         "g":241,
         "b":183
      },
      "ScaleFunction":"OutSine",
      "EndColor":{
         "r":224,
         "g":116,
         "b":67
      },
      "InheritLifeTime":false,
      "StartScale":0,
      "Angles":"{0 0 0}",
      "LifeTime":1,
      "Pos":"[0 0 0]",
      "EndRotation":-180,
      "Material":"",
      "UseEndScale":true,
      "EndScale":125,
      "UseEndRotation":true,
      "StartAxisScale":"[1 1 0]"
   },
   "Outer Ring":{
      "Enable":true,
      "Skin":0,
      "ColorFunctionMod":1,
      "Delay":0,
      "AlphaFunctionMod":1,
      "UseEndColor":true,
      "EndAlpha":0,
      "EndAxisScale":"[1 1 1]",
      "StartRotation":0,
      "RotationFunction":"Sine",
      "AxisScaleFunctionMod":1,
      "UseEndAlpha":true,
      "BodyGroups":"0",
      "AlphaFunction":"OutQuad",
      "InheritAngles":true,
      "RotationFunctionMod":1,
      "RotationNormal":"[0 0 1]",
      "Looping":false,
      "ConstantRotation":true,
      "Model":"models/metroid/effects/supermissile_ring.mdl",
      "UseEndAxisScale":true,
      "ColorFunction":"Sine",
      "StartAlpha":100,
      "ScaleFunctionMod":1.5,
      "InheritPos":false,
      "AxisScaleFunction":"OutCirc",
      "StartColor":{
         "r":255,
         "g":241,
         "b":183
      },
      "ScaleFunction":"InOutQuad",
      "EndColor":{
         "r":224,
         "g":116,
         "b":67
      },
      "InheritLifeTime":false,
      "StartScale":0,
      "Angles":"{0 0 0}",
      "LifeTime":1.1,
      "Pos":"[0 0 0]",
      "EndRotation":180,
      "Material":"",
      "UseEndScale":true,
      "EndScale":180,
      "UseEndRotation":true,
      "StartAxisScale":"[1 1 0]"
   }
}